USE sakila;

-- =========================================================
-- 1) List the number of films per category
-- =========================================================
SELECT
  c.name AS category,
  COUNT(fc.film_id) AS number_of_films
FROM category c
JOIN film_category fc
  ON c.category_id = fc.category_id
GROUP BY c.category_id, c.name
ORDER BY number_of_films DESC, category ASC;


-- =========================================================
-- 2) Retrieve the store ID, city, and country for each store
-- =========================================================
SELECT
  s.store_id,
  ci.city,
  co.country
FROM store s
JOIN address a
  ON s.address_id = a.address_id
JOIN city ci
  ON a.city_id = ci.city_id
JOIN country co
  ON ci.country_id = co.country_id
ORDER BY s.store_id;


-- =========================================================
-- 3) Calculate the total revenue generated by each store (in dollars)
-- =========================================================
SELECT
  st.store_id,
  ROUND(SUM(p.amount), 2) AS total_revenue
FROM payment p
JOIN staff sf
  ON p.staff_id = sf.staff_id
JOIN store st
  ON sf.store_id = st.store_id
GROUP BY st.store_id
ORDER BY total_revenue DESC;


-- =========================================================
-- 4) Determine the average running time of films for each category
-- =========================================================
SELECT
  c.name AS category,
  ROUND(AVG(f.length), 2) AS avg_running_time
FROM category c
JOIN film_category fc
  ON c.category_id = fc.category_id
JOIN film f
  ON fc.film_id = f.film_id
GROUP BY c.category_id, c.name
ORDER BY avg_running_time DESC, category ASC;


-- =========================================================
-- BONUS
-- =========================================================

-- 5) Film categories with the longest average running time
WITH category_avgs AS (
  SELECT
    c.name AS category,
    AVG(f.length) AS avg_running_time
  FROM category c
  JOIN film_category fc
    ON c.category_id = fc.category_id
  JOIN film f
    ON fc.film_id = f.film_id
  GROUP BY c.category_id, c.name
)
SELECT
  category,
  ROUND(avg_running_time, 2) AS avg_running_time
FROM category_avgs
WHERE avg_running_time = (SELECT MAX(avg_running_time) FROM category_avgs)
ORDER BY category;


-- 6) Top 10 most frequently rented movies (descending)
SELECT
  f.title,
  COUNT(*) AS times_rented
FROM rental r
JOIN inventory i
  ON r.inventory_id = i.inventory_id
JOIN film f
  ON i.film_id = f.film_id
GROUP BY f.film_id, f.title
ORDER BY times_rented DESC, f.title ASC
LIMIT 10;


-- 7) Determine if "Academy Dinosaur" can be rented from Store 1
SELECT
  f.title,
  CASE
    WHEN COUNT(i.inventory_id) > 0 THEN 'Yes'
    ELSE 'No'
  END AS rentable_from_store_1,
  COUNT(i.inventory_id) AS copies_in_store_1
FROM film f
LEFT JOIN inventory i
  ON f.film_id = i.film_id
 AND i.store_id = 1
WHERE f.title = 'Academy Dinosaur'
GROUP BY f.film_id, f.title;


-- 8) List all distinct film titles + availability status in inventory
WITH inv_counts AS (
  SELECT
    film_id,
    COUNT(*) AS inv_count
  FROM inventory
  GROUP BY film_id
)
SELECT
  f.title,
  CASE
    WHEN IFNULL(ic.inv_count, 0) > 0 THEN 'Available'
    ELSE 'Not available'
  END AS availability_status
FROM film f
LEFT JOIN inv_counts ic
  ON f.film_id = ic.film_id
ORDER BY f.title;
